name: Lab5 호출
on:
  workflow_dispatch:
jobs:
  release-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_type: Release
  debug-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_type: Debug
  gate:
    needs:
      - release-build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release 산출물 크기 ${{ needs.release-build.outputs.size }} byte"